### ISSUE TITLE
Troggs in Coldridge Valley linked. Bug or nah?

### ISSUE THREAD

**Issue by CarkMcBark** [Wall-core/Everlook-Bugtracker#169]
I attacked 1 Burly Rockjaw Trogg just West of where you start with Dwarfs and 2 nearby Burly Rockjaw Troggs came smashing on me.
They are yellow as in passive, so is it supposed to be like that or is it bug?
Well now you know if so.

Best regards Cark the mighty Paladin with sexy beard!

**Comment by Wall-core** [comment]
Would need comparative evidence of their linking or lack thereof from classic

**Comment by Razorkin** [comment]
Apparently this only happens in the starter area of the gnome/dwarf area for what i've seen so far. If the trogg has a trogg close nearby it will help out and start attacking you. (1-5 meters/yards)  Wolves/boars don't attack when a relative gets attacked nearby. I didn't see this behaviour in human starter area with the vermin for example. Haven't checked Night elf or horde side yet.

Sidenote:
I do like the chaining/linking, it gives a bit of challenge.

**Comment by cloudbells** [comment]
Everlook behaviour: https://youtu.be/5nXglhxk_-4?t=68
Classic behaviour: https://youtu.be/5nXglhxk_-4?t=137

They seem to be doing the exact opposite in Classic, i.e. they're running away when near a friend in combat. I haven't observed this behaviour anywhere else in Classic so it's likely just these troggs. It's funny because this is a pretty good metaphor for Classic leveling vs Everlook/pserver leveling (in a good way).

**Comment by NickTyrer** [comment]
CLosed here https://github.com/vmangos/core/commit/4e53349d678626492149344c19fa226a1ed933ee
