### ISSUE TITLE
Mob HP seems overtuned

### ISSUE THREAD

**Issue by bigglesss** [Wall-core/Everlook-Bugtracker#193]
Looking at an old Joana vid filmed during Patch 1.9.2, boars in Durator at level 2 have 55-56 HP (https://youtu.be/jTSyexUNN9E?t=122). In Everlook, they have 89-90 HP (guessing from combat log, don't have an addon installed for that).

Nostalrius PVE server (https://youtu.be/KigLZDLEgBY?t=250) has Nightsabers at roughly 43-46 HP at level 1, in Everlook they are 75-76 HP.

Northdale (https://youtu.be/mo1iqZ3iOxQ?t=1832) has Young Wolves at 42-45 HP, in Everlook they are 70-71 HP.

Mob kill times across the board in starting zones are insanely slow on the Everlook PTR, with all races I've tried.

I know there was some patch from 1.1 -> 1.12 that changed mob HP, but did it really almost half it? This seems excessive, are there any videos pre-HP adjustment that show the difference?

**Comment by ronaldofenomeno** [comment]
I noticed I was taking longer to kill mobs in Northshire as well

**Comment by cloudbells** [comment]
This is intended I believe. Mobs hit for as much as x3 the damage they do in Classic. Personally I think it's a good change since Classic is way too easy (to the point where a Mage can easily solo 3 Defias Thugs in Northshire), but as it is at the moment it's possibly a bit overtuned (to the point where aggroing a second Defias Thug is 100% death). Not sure what a good compromise is, but reducing the multiplier (for both health and damage) by an arbitrary 1/3 seems good to me. You still likely won't be able to handle 2+ mobs but one mob shouldn't be as punishing anymore.

**Comment by Gungar11** [comment]
I agree that it is over tuned. Can't complete certain normal quests that should be doable solo. And eating between every pull and 100% death from a second mob does not seem like an actual balance.

**Comment by Deprot80** [comment]
Yeah i think they went a bit too much with the overtuning. Rogues and Warriors in the starting areas were begging for someone to group up with because they couldn't kill a single mob. I was leveling together with my friend (mage+priest) and it was taking soooo long to kill one same level mob. Killing even a green level mob alone was taking forever. I don't want to fkin drink every single pull because i have to cast 15 spells to kill something.

I played vanillagaming, nost, kronos 1,2,3, elysium, LH, hyjal, darrowshire and blizzard classic. None of them had it that much overtuned.

**Comment by ohmygoshoctopus** [comment]
I felt the same way (as a druid in Mulgore), but I did feel that:
- the biggest issue had something to do with the amount of damage received when fighting higher-level mobs. If I fought a level 2 (as level 2), I was fine. If I fought a level 3 (as a level 2), I had to pay attention and would often lose more than 50% of my HP.
- this issue basically resolved itself by level 5. Things felt "normal" once I left the starting area.

My best guess was that the level 1-4 mobs in the "tutorial" areas were probably a little overtuned, but maybe more due to the interaction of weapon/defense skills than HP, although you're absolutely right that they also seem to have more HP.
