### ISSUE TITLE
Pathing issues in Wailing Caverns

### ISSUE THREAD

**Issue by grapedaddy** [Wall-core/Everlook-Bugtracker#2]
![image](https://user-images.githubusercontent.com/44329140/173704327-aa692509-92e8-4c9e-8abc-fc620039cd7c.png)

You can see the Deviate Ravager corpse above me. That's where I was standing when I attacked it. It was down below on the ground. The mob, instead of going around, instead directly climbed the wall.

**Comment by grapedaddy** [comment]
![image](https://user-images.githubusercontent.com/44329140/173709614-39e14a2b-6378-4011-b93a-a4b66b612dae.png)

Evolving Ectoplasm paths underground and becomes impossible to target. Later it does path back above ground. Exact location:

![image](https://user-images.githubusercontent.com/44329140/173709679-fd5afc38-ab81-4edf-9c61-1f6df6451866.png)

**Comment by Simp-N** [comment]
I don't know if it's related, but several Serpentblooms are very difficult to loot because they're difficult to target (as in the cogwheel-icon appearing). The serpentbloom visually appears fine, but the lootable object is seems like it's sunken into the ground. You have to wave your cursor over them a bit to get the cogwheel-icon to appear. I might make a separate post once I've tested more exactly which ones are affected, but I thought I'd mention it here since it's possible the issues are related.

**Comment by NickTyrer** [comment]
Closed Here https://github.com/vmangos/core/pull/1467

**Comment by NickTyrer** [comment]
The serpentbloom issue seems to be a client bug (the client prioritises the trap rather than the lootable data). Although this cant be fixed in vmangos the server owner can make the trap invisible using `UPDATE `gameobject_template` SET `flags` = 0,  `displayId` = 0 WHERE `entry` = 19535;`
