### ISSUE TITLE
Orcs racial not working properly

### ISSUE THREAD

**Issue by ronaldinho161** [Wall-core/Everlook-Bugtracker#278]
Blood fury does not grant bonus melee AP.
Healing reduce works fine.

**Comment by ronaldofenomeno** [comment]
Hello little brother

**Comment by Xazamas** [comment]
Bonus melee AP and healing Reduction are separate buff and debuff, and the debuff lasts longer. Just in case the issue is you ran out of the buff and think you only get the debuff.

This is the buff https://classic.wowhead.com/spell=23234/blood-fury

Further testing (server down so I can't do it myself right now) is to check if A) the buff is applied B) if so, does it increase AP (Attack Power.)
