### ISSUE TITLE
LoS in Ruins of Mathystra

### ISSUE THREAD

**Issue by Snoker** [Wall-core/Everlook-Bugtracker#322]
The pillars in Ruins of Mathystra doesn'thave any LoS so mobs can see and shoot you through them. See example picture of pillars that the mobs can shoot frostbolt through
![image](https://user-images.githubusercontent.com/3244574/196005447-855257d5-ca94-4f48-8bdd-d5210f2663cd.png)

**Comment by Snoker** [comment]
This also applies to trees and walls. Neither below tree or wall inbetween me and the naga stops her from shooting me
![image](https://user-images.githubusercontent.com/3244574/196005542-6281fbd6-053d-4943-a26f-41c3ee760db5.png)

**Comment by FlagFlayer** [comment]
This is the behaviour for all objects in vmangos. I believe Kronos changed this so these objects block line of sight, which makes dealing with caster mobs quite easy as long as there's an object nearby to kite the mob around. This object not breaking LoS behvaiour has been around for years, probably in order to not make caster mobs incredibly weak and prone to simple kiting for easy kills.
