### ISSUE TITLE
Lunaclaw Alliance + Shadowglen Deathskip + Felcones

### ISSUE THREAD

**Issue by Bornlesszero** [Wall-core/Everlook-Bugtracker#326]
I killed her outside cuz I used few roots. Didn't get credit.
Also, when you die in Shadowglen, U respawn in Dolanaar.
Also, there are like 6 to 8 spawn points only when it should be 30-50++

**Comment by FlagFlayer** [comment]
It was hard to figure out what you're talking about as you gave very minimal comments but for your information:

1) You don't complete the quest by killing Lunaclaw, but by talking to its blue-ish spirit which spawns after its death.

2) The graveyard issues with starting zones has been fixed in the latest server update.

3) Fel cones have a limited amount of spawns. While they can spawn in many different locations, there will be only a few that will be spawned at any one time. The object Fel Cone [1673] needs a dynamic respawn to be implemented for this reason.

**Comment by Bornlesszero** [comment]
> It was hard to figure out what you're talking about as you gave very minimal comments but for your information:
> 
> 1. You don't complete the quest by killing Lunaclaw, but by talking to its blue-ish spirit which spawns after its death.
> 2. The graveyard issues with starting zones has been fixed in the latest server update.
> 3. Fel cones have a limited amount of spawns. While they can spawn in many different locations, there will be only a few that will be spawned at any one time. The object Fel Cone [1673] needs a dynamic respawn to be implemented for this reason.

Hi Flag! I killed Lunaclaw outside and talked to the spirit and couldn't complete quest or get credit.

**Comment by Bornlesszero** [comment]
Hi Flag! I killed Lunaclaw outside and talked to the spirit and couldn't complete quest or get credit.

**Comment by FlagFlayer** [comment]
You have to talk to the spirit and then click on the dialogue option that you have, that will complete the quest.
