### ISSUE TITLE
Floaty Boat Corpse

### ISSUE THREAD

**Issue by ohmygoshoctopus** [Wall-core/Everlook-Bugtracker#348]
Player corpses stay attached to their absolute geography and do not travel with boats - although, admittedly, I don't know whether they are supposed to or not. But there was a body oddly floating in the air above the Ratchet port. Here are pictures, with and without the boat:

![WoWScrnShot_101722_015832](https://user-images.githubusercontent.com/30633449/196111084-2806ecdf-9ff6-4db7-9d3e-8b88e42fef74.png)

![WoWScrnShot_101722_015927](https://user-images.githubusercontent.com/30633449/196111105-ba06537b-d861-40af-a37e-6aa59b60a44e.png)

**Comment by FlagFlayer** [comment]
This has been the behaviour of corpses on private servers for as long as I can remember (at least 7 years back). I'm pretty sure that if this wasn't intended behvaiour or was able to be changed/"fixed" it would've been by now, though it doesn't hurt to look into.

**Comment by Wall-core** [comment]
It's due to how corpses are handled as gameobjects, not creatures. Splines and motion are not handled for gameobjects in vanilla wow; It can be enabled but is low priority, and not blizzlike. Corpses should stay at their death position due to how boats work; If they stayed on the boat, they would eventually reach the end of the path and then the boat would disappear and drop them into unrecoverable spots.
