### ISSUE TITLE
Cant use ColdBlood + Eviscerate in 1 keypress

### ISSUE THREAD

**Issue by laytya** [Wall-core/Everlook-Bugtracker#402]
ColdBlood disapear if using in macro

/cast Cold Blood
/run SpellStopCasting()
/cast Eviscerate

Cold Blood - instant and dont have GCD

Similar spells are workig such as Nature's Swiftness

Also bug w/ Cheap Shot - it starts auto attack - but it should not. I have old macros from 1.12 - there are i manualy start autoattack w/ Cheap Shot.

**Comment by wonderlandx** [comment]
cheap shot always starts auto attack.

**Comment by wonderlandx** [comment]
/cast Cold Blood
/cast Eviscerate
works fine.

your macro is missing a space in Cold Blood.

**Comment by laytya** [comment]
its work only at 2 key presses not 1

**Comment by laytya** [comment]
> cheap shot always starts auto attack.

do u have evidence of it? "Always"

**Comment by wonderlandx** [comment]
I know because sap cheap shot expose armor is a common duel opener and it involves turning away from the target after cheap shot and often using a macro as well to prevent auto attack breaking sap.

your 1.12 macro is obviously wrong. if you put start attack with a stealth ability its going to break stealth randomly by auto attacking the target.

**Comment by wonderlandx** [comment]
I know because sap cheap shot expose armor is a common duel opener and it involves turning away from the target after cheap shot/using a macro to prevent auto attack breaking sap.

your 1.12 macro is obviously wrong. if you put start attack with a stealth ability its going to break stealth randomly by auto attacking the target.

**Comment by laytya** [comment]
CB macro not wrong - it works w/ NS for Sham and Dru
its worked and w/ CB, but now not

**Comment by Gamemechanicwow** [comment]
> > cheap shot always starts auto attack.
> 
> do u have avidance of it? "Always"

Go to your wow folder.
Open "data/dbc.mpq" and extract "dbfilesclient\spell.dbc"
Use a viewer to find the spell and look at the damn attributes.

notice the flag for SPELL_ATTR1_MELEE_COMBAT_START is set.

That's a small introduction to how spell data is datamined.

The client (not the server) sends a CMSG_ATTACKSWING packet which initiates autoattack, - this is observable with packet sniffing.

**Comment by laytya** [comment]
> > > cheap shot always starts auto attack.
> > 
> > 
> > do u have avidance of it? "Always"
> 
> Go to your wow folder. Open "data/dbc.mpq" and extract "dbfilesclient\spell.dbc" Use a viewer to find the spell and look at the damn attributes.
> 
> notice the flag for SPELL_ATTR1_MELEE_COMBAT_START is set.
> 
> That's a small introduction to how spell data is datamined.
> 
> The client (not the server) sends a CMSG_ATTACKSWING packet which initiates autoattack, - this is observable with packet sniffing.

This "Big" evidence. What about CB+Evisc?
