### ISSUE TITLE
Logging out kicks characters from group

### ISSUE THREAD

**Issue by Tessablanc** [Wall-core/Everlook-Bugtracker#474]
While in Strat we had a mage relog to fix his addons, which kicked him from the group and put him outside the instance. Regardless of whether this "feature" was blizzlike in vanilla, it is a huge pain in the ass and really shouldn't exist due to the number of bugs that relogging fixes, and how often it's necessary to do it.

**Comment by Wall-core** [comment]
you can alt+f4 to close client without being removed from party. It's how 1.12 handles logout request; it could be changed to work different but that would nerf a major benefit of it in that you can reset an instance easily by logging out and returning to the entrance while in a party. Otherwise if you need to reload client, do alt+f4 to avoid this.
