### ISSUE TITLE
Flight master standing in wrong zone and nonfunctional

### ISSUE THREAD

**Issue by mmekaplan** [Wall-core/Everlook-Bugtracker#501]
Shaethis Darkoak, flight master, is standing near the Leatherworking Supplies vendor Zannok Hidepiercer in Silithus instead of at his post in Un'goro.
![2022-11-01_11-48-04](https://user-images.githubusercontent.com/54257398/199276653-388d29a5-130f-49a1-8275-6e58a71e30f0.png)

**Comment by Gamemechanicwow** [comment]
In 1.2 the un'goro fligtmasters were placed there. You will see the horde flightmaster on the other side of the road.

That flightpath no longer exists in the 1.12 client. So they appear buggy.

**Comment by Daribon** [comment]
> In 1.2 the un'goro fligtmasters were placed there. You will see the horde flightmaster on the other side of the road.
> 
> That flightpath no longer exists in the 1.12 client. So they appear buggy.

As the above comment gave incorrect information let me clarify.

Between patch 1.3 and patch 1.7 the flight masters in Silithus were spawned in Valor's Rest. Before patch 1.8 Cenarion Hold did not exist. Since Everlook is running the 1.12.1 client and not an older client, it will appear as the Flight Master should be in Un'goro.
