### ISSUE TITLE
Wetland's Croco Quest Not available

### ISSUE THREAD

**Issue by Bornlesszero** [Wall-core/Everlook-Bugtracker#526]
Lvl 20-21 Croco Quest no where to be found in Wetlands.
Young Crocolisks

**Comment by Simp-N** [comment]
It appears that in vmangos the quest [Young Crocolisk Skin](https://classicdb.ch/?quest=484) requires the quest [Daily Delivery](https://classicdb.ch/?quest=469), which may be why you couldn't pick it up.

Looking on Wowhead from this quests ([YCS](https://www.wowhead.com/classic/quest=484/young-crocolisk-skins#comments), [DD](https://www.wowhead.com/classic/quest=469/daily-delivery#comments)) there is no mention of this requirement, and no comment mentions it. [Video from Classic](https://youtu.be/eoC47BaKUtk?t=238), go to 3:58, showing that he can pick up YCS before turning in DD.

Daily Delivery is obviously meant as a bread-crumb quest for Menethil harbour, but I'm guessing it's been mistakenly marked as a pre-q since they both involve Crocodile skins.

I couldn't find any source from actual vanilla though.

**Comment by Tessablanc** [comment]
Daily Delivery actually is a prequest for this, as per 2006 info: https://web.archive.org/web/20060515023223/http://wow.allakhazam.com/db/quest.html?wquest=484
