### ISSUE TITLE
strat rats bugged, random dropping out of combat

### ISSUE THREAD

**Issue by cronichar** [Wall-core/Everlook-Bugtracker#78]
spawned rats (from boxes, door event) in strat are bugged, they are passive (they are not attacking) are randomly go inside a wall where they cant be attacked
also, players dropping out of combat during fight if person who pulled mobs dies mobs reset (happened in BRD and STRAT)

**Comment by Roflkopterr** [comment]
"players dropping out of combat during fight if person who pulled mobs dies mobs reset"

That is intended and has been this way since I can remember. If someone pulls a mob and only THEY are on the threat table and you take no action so you gain no threat even if your in combat the mobs will reset once that person dies.

Are you stating combat is dropped even though the non pulling players damaged a mob or healed the guy who pulled?

**Comment by ratkosrb** [comment]
Rats not attacking fixed in https://github.com/vmangos/core/commit/3b8ddafc7f248a056bd6861b2917d95ef9860fe0

**Comment by cronichar** [comment]
Are you stating combat is dropped even though the non pulling players damaged a mob or healed the guy who pulled? 

exactly, that was the case. we attacked mobs when they came to us and when the player who pulled died they went back to their position
